spring:
  # H2 데이터베이스 설정
  datasource:
    driver-class-name: org.h2.Driver  # H2 DB를 사용하기 위한 드라이버
    url: jdbc:h2:./db_dev;MODE=MySQL  # H2 DB 파일 경로 + MySQL 모드 (문법 비슷하게 사용 가능)
    username: sa                      # 기본 사용자 이름
    password:                         # 기본 비밀번호 (없음)

  # H2 웹 콘솔 설정 (브라우저에서 DB 확인할 수 있음)
  h2:
    console:
      enabled: true        # H2 콘솔 사용 가능하게 함
      path: /h2-console    # 접속 주소: http://localhost:8080/h2-console

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # JPA가 사용할 DB 종류 (H2 전용 설정)
