spring:
  # MySQL 데이터베이스 연결 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC 드라이버
    url: jdbc:mysql://localhost:3306/{실제 DB 이름 입력}?serverTimezone=Asia/Seoul&useSSL=false
    username: your_username     # DB 사용자 이름
    password: your_password     # DB 비밀번호

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL 8 버전에 맞는 JPA 방언
    hibernate:
      ddl-auto: update              # 테이블 자동 생성/수정 (운영에선 none 추천)
    properties:
      hibernate:
        format_sql: true           # SQL 예쁘게 출력
        show_sql: true             # 실행되는 SQL 출력
